### ISSUE TITLE
Problem with export

### ISSUE THREAD

**Issue by Mayki07** [matyalatte/UE4-DDS-Tools#9]
Hey. I'm using your great tool and it's a really big help. However, I ran into a problem where I can't export one texture. Could you please take a look at it?
I am attaching a file to test.

[Test_file.zip](https://github.com/matyalatte/UE4-DDS-Tools/files/9991131/Test_file.zip)

![Version checker](https://user-images.githubusercontent.com/35667524/201368906-ae4d0955-99a1-4397-bdeb-3a4e5b6b6b0a.jpg)

**Comment by matyalatte** [comment]
Sorry for the late reply.
The cause was that it used an unsupported pixel format (PF_ASTC_4X4).
So, I added support for PF_ASTC_4X4, and made the check mode raise an error when unsupported formats are detected (at 6c256b45e3972b963759095a1a80ed00b164715c).

Here is a build from the latest commit (9290707a41ed95c1bf3a5698ef43d43d2c6d933b).
[UE4-DDS-Tools-v0.3.3.zip](https://github.com/matyalatte/UE4-DDS-Tools/files/10272966/UE4-DDS-Tools-v0.3.3.zip)
You can get dds from the test file with it.

But please note that you can't export the textures as non-DDS files (because ASTC is a non-official DDS format and my DDS converter doesn't support it.)
Export it as dds first. Then, you can open it with other tools like NVIDIA Texture Tools.

**Comment by Mayki07** [comment]
Hi, thanks for modifying the program, it works perfectly now.
